#!/usr/bin/env python

import sys
import os
import openbabel as ob
import pybel

# NIH resolver interface
import cirpy

outOptions = {}
outOptions['f'] = "keywords"

# read through multiple files on command-line
for argument in sys.argv[1:]:
    fileName, fileExt = os.path.splitext(argument)
    print >> sys.stderr, fileName
    try:
        for molecule in pybel.readfile(fileExt[1:], argument):
            inchi = molecule.write("inchi").rstrip()
            ikey = molecule.write("inchikey").rstrip()

            name = None
            try:
                name = cirpy.resolve(inchi, 'iupac_name')
            except Exception:
                pass

            if type(name) is list:
                name = name[0]
            if name is None:
                name = "none"

            print ikey, '\"%s\"' % name.lower()

            mopacName = "pm7/%s/%s/%s" % (ikey[0], ikey[1], ikey)
            if not os.path.isfile(mopacName):
                out = pybel.Outputfile("mopin", "%s.mop" % mopacName, True, outOptions)
                out.write(molecule)
                out.close()
    except Exception:
        pass
