#!/usr/bin/env python

import sys, os
from distutils.dir_util import mkpath

import pybel

# MOPAC keywords for geometry optimization
outOptions = {}
outOptions['k'] = " BFGS PM7 MMOK PRECISE"

# read through multiple files on command-line
for argument in sys.argv[1:]:
    fileName, fileExt = os.path.splitext(argument)
    print >> sys.stderr, fileName
    try:
        for molecule in pybel.readfile(fileExt[1:], argument):
            ikey = molecule.write("inchikey").rstrip()

            mopacName = "pm7/%s/%s.mop" % (ikey[0:2], ikey)
            mkpath("pm7/%s" % (ikey[0:2]))
            if not os.path.isfile(mopacName):
                out = pybel.Outputfile("mopcrt", mopacName, True, outOptions)
                out.write(molecule)
                out.close()
    except Exception:
        pass
