#!/usr/bin/env python

import sys, os
from distutils.dir_util import mkpath

import pybel
ob = pybel.ob

# read through multiple (large) files on command-line
# split them into multiple mol2 named by InChI Keys for later processing
for argument in sys.argv[1:]:
    fileName, fileExt = os.path.splitext(argument)

    print "splitting file: ", argument
    for molecule in pybel.readfile(fileExt[1:], argument):
        try:
            ikey = molecule.write("inchikey").rstrip()
            # give the inchi key and name
            print ikey
            if len(ikey) != 27:
                continue

            fileName = 'library/%s/%s/%s.mol2' % (ikey[0], ikey[1], ikey)
            mkpath('library/%s/%s' % (ikey[0], ikey[1]))
            molecule.write('mol2', fileName)
        except IOError:
            continue # next file
