#!/usr/bin/env python

import sys, os
from distutils.dir_util import mkpath

import pybel
ob = pybel.ob

# read through multiple (large) files on command-line
# split them into multiple SDF named by InChI Keys for later processing
for argument in sys.argv[1:]:
    fileName, fileExt = os.path.splitext(argument)

    try:
        for molecule in pybel.readfile(fileExt[1:], argument):
            ikey = molecule.write("inchikey").rstrip()

            fileName = 'library/%s/%s/%s' % (ikey[0], ikey[1], ikey)
            mkpath('library/%s/%s' % (ikey[0], ikey[1]))
            mol.write('sdf', '%s.sdf' % fileName)